name: driver_config
description: Optimize a wind, PV, and battery hybrid plant using native H2I models
general:
  folder_output: wind_pv_battery_run
driver:
  optimization:
    flag: true
    tol: 0.01
    max_iter: 6
    solver: COBYLA
    rhobeg: 0.2
    debug_print: true
    autoscaler: bounds
design_variables:
  wind:
    wind_turbine_rating:
      flag: true
      lower: 0.0
      upper: 5000.0
      units: kW
  solar:
    system_capacity_DC:
      flag: true
      lower: 0.0
      upper: 22000.0
      units: kW
  battery:
    max_charge_rate:
      flag: true
      lower: 0.0
      upper: 22000.0
      units: kW
    storage_capacity:
      flag: true
      lower: 0.0
      upper: 22000.0
      units: kW*h
constraints:
  electrical_load_demand:
    percent_load_missed:
      flag: true
      lower: 20.
      units: percent
    curtailment_percent:
      flag: true
      lower: 20.0
      units: percent
  battery:
    storage_duration:
      flag: true
      upper: 10
      units: h
objective:
  name: finance_subgroup_default.LCOE
