name: technology_config
description: This hybrid plant produces hydrogen
technologies:
  distributed_wind_plant:
    performance_model:
      model: FlorisWindPlantPerformanceModel
    cost_model:
      model: GenericConverterCostModel
    model_inputs:
      performance_parameters:
        num_turbines: 100  # number of turbines in the farm
        hub_height: 65.0  # turbine hub-height
        operational_losses: 12.83  # percentage of non-wake losses
        floris_wake_config: !include "floris_v4_default_template.yaml" #floris wake model file
        floris_turbine_config: !include "floris_turbine_Vestas_660kW.yaml" #turbine model file formatted for floris
        resource_data_averaging_method: weighted_average   #"weighted_average", "average" or "nearest"
        operation_model: cosine-loss  # turbine operation model
        default_turbulence_intensity: 0.06
        enable_caching: true  # whether to use cached results
        cache_dir: cache  # directory to save or load cached data
        layout:
          layout_mode: basicgrid
          layout_options:
            row_D_spacing: 5.0
            turbine_D_spacing: 5.0
            rotation_angle_deg: 0.0
            row_phase_offset: 0.0
            layout_shape: square
      cost_parameters:
        commodity: electricity
        commodity_rate_units: kW
        commodity_amount_units: kW*h
        unit_capex: 2286  # USD/kW distributed wind capex for 2030
        unit_opex: 38  # USD/kW/year
        unit_varopex: 0.0  # USD/kW*h/year
        cost_year: 2022
      financial_parameters:
        capital_items:
          depr_period: 7  # 7 year depreciation period
          replacement_cost_percent: 0.15  # cost of stack replacement is 15% of CapEx
  distributed_pv:
    performance_model:
      model: PYSAMSolarPlantPerformanceModel
    cost_model:
      model: ATBResComPVCostModel
    model_inputs:
      shared_parameters:
        pv_capacity_kWdc: 50000  # 50 MWdc
      performance_parameters:
        dc_ac_ratio: 1.23  # pv inverter capacity is equal to 50 MWdc/1.22
        create_model_from: new
        tilt_angle_func: none
        tilt: 20.0
        pysam_options:
          SystemDesign:
            array_type: 0  # fixed open rack
            inv_eff: 98.0  # inverter losses
            bifaciality: 0.0
            module_type: 0  # standard, 19% efficiency
            losses: 10.0  # DC losses
            azimuth: 0  # North facing
            gcr: 0.2  # groud coverage ratio
          SolarResource:
            use_wf_albedo: false  # don't use albedo from weather file
            albedo_default: 0.3
          Lifetime:
            dc_degradation: [0]
      cost_parameters:
        capex_per_kWdc: 1492  #$/kWdc
        opex_per_kWdc_per_year: 16.0  # $/kWDC/year
        cost_year: 2022
  gen_combiner:  # combiner for generation, pv + wind
    performance_model:
      model: GenericCombinerPerformanceModel
    model_inputs:
      shared_parameters:
        commodity: electricity
        commodity_rate_units: kW
  battery:
    performance_model:
      model: StoragePerformanceModel
    cost_model:
      model: GenericStorageCostModel
    control_strategy:
      model: DemandOpenLoopStorageController
    model_inputs:
      shared_parameters:
        commodity: electricity
        commodity_rate_units: MW
        commodity_amount_units: MW*h
        max_charge_rate: 12.0  # equal to 2x electrolyzer turndown ratio, 12 MW
        max_capacity: 48.0  # 4-hour battery, 48 MW
        init_soc_fraction: 0.0
        charge_equals_discharge: true
        charge_efficiency: 1.0
        discharge_efficiency: 1.0
        min_soc_fraction: 0.0
        max_soc_fraction: 1.0
        demand_profile: 6.0  # equal to electrolyzer turndown ratio (6 MW)
      cost_parameters:
        capacity_capex: 173000  # USD/MW*h, 173 USD/kW*h
        charge_capex: 750000  # USD/MW (multiplied by charge rate), 750 USD/kW
        opex_fraction: 0.025  # 2.5 % of total CapEx
        cost_year: 2022
  elec_combiner:  # combiner for battery + generation
    performance_model:
      model: GenericCombinerPerformanceModel
    model_inputs:
      shared_parameters:
        commodity: electricity
        commodity_rate_units: kW
  elec_load_demand:  # load demand component for electrolyzer
    performance_model:
      model: GenericDemandComponent
    model_inputs:
      performance_parameters:
        commodity: electricity
        commodity_rate_units: MW
        demand_profile: 60  # Equal to electrolyzer capacity
  electrolyzer:
    performance_model:
      model: ECOElectrolyzerPerformanceModel
    cost_model:
      model: CustomElectrolyzerCostModel
    model_inputs:
      performance_parameters:
        location: onshore
        size_mode: normal
        n_clusters: 6  # number of 10 MW clusters
        cluster_rating_MW: 10  # 10 MW clusters
        eol_eff_percent_loss: 10  # eol defined as x% change in efficiency from bol
        uptime_hours_until_eol: 80000.  # number of 'on' hours until electrolyzer reaches eol
        include_degradation_penalty: true  # include degradation
        turndown_ratio: 0.1  # turndown_ratio = minimum_cluster_power/cluster_rating_MW
        electrolyzer_capex: 1000  # only used for electrolyzer performance
      cost_parameters:
        capex_USD_per_kW: 1000.0
        fixed_om_USD_per_kW_per_year: 12.8
        cost_year: 2022
      financial_parameters:
        capital_items:
          depr_period: 7  # based on PEM Electrolysis H2A Production Case Study Documentation estimate of 7 years. also see https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
          replacement_cost_percent: 0.15  # percent of capex - H2A default case
