name: technology_config
description: This plant has offshore wind and battery connected to a ocean alkalinity enhancement device
technologies:
  wind:
    performance_model:
      model: FlorisWindPlantPerformanceModel
    cost_model:
      model: ATBWindPlantCostModel
    dispatch_rule_set:
      model: PyomoDispatchGenericConverter
    model_inputs:
      performance_parameters:
        num_turbines: 22  # number of turbines in the farm
        hub_height: 150.0  # turbine hub-height
        operational_losses: 12.83  # percentage of non-wake losses
        floris_wake_config: !include "floris_v4_default_template.yaml" #floris wake model file
        floris_turbine_config: !include "floris_turbine_osw_15MW.yaml" #turbine model file formatted for floris
        resource_data_averaging_method: average   #"weighted_average", "average" or "nearest"
        operation_model: cosine-loss  # turbine operation model
        default_turbulence_intensity: 0.06
        enable_caching: true  # whether to use cached results
        cache_dir: cache  # directory to save or load cached data
        layout:
          layout_mode: basicgrid
          layout_options:
            row_D_spacing: 7.0
            turbine_D_spacing: 7.0
            rotation_angle_deg: 0.0
            row_phase_offset: 0.0
            layout_shape: square
      cost_parameters:
        capex_per_kW: 9390
        opex_per_kW_per_year: 72
        cost_year: 2022
      dispatch_rule_parameters:
        commodity: electricity
        commodity_rate_units: kW
  battery:
    dispatch_rule_set:
      model: PyomoRuleStorageBaseclass
    control_strategy:
      model: HeuristicLoadFollowingStorageController
    performance_model:
      model: PySAMBatteryPerformanceModel
    cost_model:
      model: ATBBatteryCostModel
    model_inputs:
      shared_parameters:
        commodity: electricity
        commodity_rate_units: kW
        max_charge_rate: 50000  # kW
        max_capacity: 200000  # kWh
        init_soc_fraction: 0.9
        max_soc_fraction: 1.0
        min_soc_fraction: 0.2
      performance_parameters:
        chemistry: LFPGraphite
        demand_profile: 330000  # 330 MW
      cost_parameters:
        cost_year: 2022
        energy_capex: 246  # $/kWh from 2024 ATB year 2025
        power_capex: 317  # $/kW from 2024 ATB year 2025
        opex_fraction: 0.02536510376633359
      control_parameters:
        n_control_window: 24
        system_commodity_interface_limit: 1e12
  combiner:
    performance_model:
      model: GenericCombinerPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: electricity
        commodity_rate_units: kW
  oae:
    performance_model:
      model: OAEPerformanceModel
    cost_model:
      model: OAECostModel
    model_inputs:
      performance_parameters:
        number_ed_min: 1
        number_ed_max: 10
        max_ed_system_flow_rate_m3s: 0.0324  # m^3/s
        frac_base_flow: 0.5
        assumed_CDR_rate: 0.8  # mol CO2/mol NaOH
        use_storage_tanks: true
        initial_tank_volume_m3: 0.  # m^3
        store_hours: 12.  # hours
        acid_disposal_method: sell rca
        initial_salinity_ppt: 73.76  # ppt
        initial_temp_C: 10.0  # degrees Celsius
        initial_dic_mol_per_L: 0.0044  # mol/L
        initial_pH: 8.1  # initial pH
        save_outputs: true
      cost_parameters:
        mass_product_tonne_yr: 100000.0
