name: plant_config
description: This plant is located in MN, USA...
sites:
  site:
    latitude: 41.717
    longitude: -88.398
technology_interconnections:
  # Connect feedstocks to iron mine.
  - [mine_electricity_feedstock, iron_mine, electricity, cable]
  - [mine_crude_ore_feedstock, iron_mine, crude_ore, crude_ore_transport]
  # Connect iron_ore price and processed_ore_feedstock to iron_transport
  # Connect the LCOI of iron ore to the price of a feedstock component representing the ore to be used in DRI
  - [finance_subgroup_iron_ore, processed_ore_feedstock, [price_iron_ore, price]]
  # Connect the ore feedstock available to the iron plant
  - [processed_ore_feedstock, iron_plant, iron_ore, iron_ore_transport]
  - [dri_grid_feedstock, iron_plant, electricity, cable]
  - [catalyst_feedstock, iron_plant, reformer_catalyst, catalyst_transport]
  - [water_feedstock, iron_plant, water, pipe]
  - [natural_gas_feedstock, iron_plant, natural_gas, pipe]
  # Use the iron ore consumed by the iron plant to calculate transport costs
  - [iron_plant, iron_transport, [iron_ore_consumed, iron_ore_in]]
  # Connect feedstocks to steel plant
  - [eaf_grid_feedstock, steel_plant, electricity, cable]
  - [eaf_water_feedstock, steel_plant, water, pipe]
  - [eaf_natural_gas_feedstock, steel_plant, natural_gas, pipe]
  - [iron_plant, steel_plant, pig_iron, pig_iron_transport]
plant:
  plant_life: 30
  simulation:
    n_timesteps: 8760
    dt: 3600
    timezone: 0
finance_parameters:
  finance_groups:
    finance_model: ProFastLCO
    model_inputs:
      params:
        analysis_start_year: 2032
        installation_time: 36  # months
        inflation_rate: 0.0  # 0 for nominal analysis
        discount_rate: 0.09  # nominal return based on 2024 ATB baseline workbook for land-based wind
        debt_equity_ratio: 2.62  # 2024 ATB uses 72.4% debt for land-based wind
        property_tax_and_insurance: 0.03  # percent of CAPEX estimated based on https://www.nlr.gov/docs/fy25osti/91775.pdf  https://www.house.mn.gov/hrd/issinfo/clsrates.aspx
        total_income_tax_rate: 0.257  # 0.257 tax rate in 2024 atb baseline workbook, value here is based on federal (21%) and state in MN (9.8)
        capital_gains_tax_rate: 0.15  # H2FAST default
        sales_tax_rate: 0.07375  # total state and local sales tax in St. Louis County https://taxmaps.state.mn.us/salestax/
        debt_interest_rate: 0.07  # based on 2024 ATB nominal interest rate for land-based wind
        debt_type: Revolving debt  # can be "Revolving debt" or "One time loan". Revolving debt is H2FAST default and leads to much lower LCOH
        loan_period_if_used: 0  # H2FAST default, not used for revolving debt
        cash_onhand_months: 1  # H2FAST default
        admin_expense: 0.00  # percent of sales H2FAST default
      capital_items:
        depr_type: MACRS   # can be "MACRS" or "Straight line"
        depr_period: 5  # 5  years - for clean energy facilities as specified by the IRS MACRS schedule https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
        refurb: [0.]
  cost_adjustment_parameters:
    cost_year_adjustment_inflation: 0.025
    target_dollar_year: 2022
  finance_subgroups:
    iron_ore:
      commodity: iron_ore
      commodity_stream: iron_mine
      technologies:
        - iron_mine
        - mine_electricity_feedstock
        - mine_crude_ore_feedstock
    pig_iron:
      commodity: pig_iron
      commodity_stream: iron_plant
      technologies:
        - processed_ore_feedstock
        - iron_transport
        - iron_plant
        - dri_grid_feedstock
        - catalyst_feedstock
        - water_feedstock
        - natural_gas_feedstock
    steel:
      commodity: steel
      commodity_stream: steel_plant
      technologies:
        - processed_ore_feedstock
        - iron_transport
        - iron_plant
        - dri_grid_feedstock
        - catalyst_feedstock
        - water_feedstock
        - natural_gas_feedstock
        - eaf_water_feedstock
        - eaf_natural_gas_feedstock
        - eaf_grid_feedstock
        - steel_plant
