name: technology_config
description: This hybrid plant produces iron
technologies:
  mine_electricity_feedstock:  # electricity feedstock for iron ore
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: electricity
        commodity_rate_units: MW
      performance_parameters:
        rated_capacity: 30.  # MW, need 27.913 MW per timestep for iron ore
      cost_parameters:
        cost_year: 2022
        price: 0.  # Electricity costs are already priced in to current mine model
        annual_cost: 0.
        start_up_cost: 0.
  mine_crude_ore_feedstock:  # iron ore feedstock
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: crude_ore
        commodity_rate_units: t/h
      performance_parameters:
        rated_capacity: 2000.  # need 828.50385048 t/h
      cost_parameters:
        cost_year: 2022
        price: 0.  # USD/t
        annual_cost: 0.
        start_up_cost: 0.
  crude_ore_transport:
    performance_model:
      model: GenericTransporterPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: crude_ore
        commodity_rate_units: t/h
  iron_mine:
    performance_model:
      model: MartinIronMinePerformanceComponent
    cost_model:
      model: MartinIronMineCostComponent
    model_inputs:
      shared_parameters:
        mine: Northshore
        taconite_pellet_type: drg
        max_ore_production_rate_tonnes_per_hr: 221.2592636
  iron_ore_transport:
    performance_model:
      model: GenericTransporterPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: iron_ore
        commodity_rate_units: kg/h
  processed_ore_feedstock:  # iron ore feedstock
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: iron_ore
        commodity_rate_units: t/h
      performance_parameters:
        rated_capacity: 250.  # need 828.50385048 t/h
      cost_parameters:
        cost_year: 2022
        price: 0.0
        annual_cost: 0.
        start_up_cost: 0.
  iron_transport:
    performance_model:
      model: IronTransportPerformanceComponent
    cost_model:
      model: IronTransportCostComponent
    model_inputs:
      performance_parameters:
        find_closest_ship_site: false
        shipment_site: Chicago
      cost_parameters:
        transport_year: 2022
        cost_year: 2022
  natural_gas_feedstock:
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: natural_gas
        commodity_rate_units: MMBtu/h
      performance_parameters:
        rated_capacity: 1270.  # need 1268.934 MMBtu/h
      cost_parameters:
        cost_year: 2022
        price: 4.0  # USD 4.0/MMBtu
        annual_cost: 0.
        start_up_cost: 0.
  water_feedstock:  # for iron reduction
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: water
        commodity_rate_units: galUS  # galUS/h
      performance_parameters:
        rated_capacity: 40000.  # need 38710.49649 galUS/h
      cost_parameters:
        cost_year: 2022
        price: 0.0016700004398318847  # cost is USD 0.441167535/t, converted to USD/gal
        annual_cost: 0.
        start_up_cost: 0.
  catalyst_feedstock:  # for NG iron reduction
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: reformer_catalyst
        commodity_rate_units: (m**3)  # m**3/h
      performance_parameters:
        rated_capacity: 0.001  # need 0.00056546 m**3/h
      cost_parameters:
        cost_year: 2022
        price: 17515.14  # USD 17515.14/m**3
        annual_cost: 0.
        start_up_cost: 0.
  catalyst_transport:
    performance_model:
      model: GenericTransporterPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: reformer_catalyst
        commodity_rate_units: (m**3)
  dri_grid_feedstock:  # electricity feedstock for iron dri
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: electricity
        commodity_rate_units: kW
      performance_parameters:
        rated_capacity: 27000.  # need 26949.46472431 kW
      cost_parameters:
        cost_year: 2022
        price: 0.05802  # USD/kW
        annual_cost: 0.
        start_up_cost: 0.
  iron_plant:
    performance_model:
      model: NaturalGasIronReductionPlantPerformanceComponent
    cost_model:
      model: NaturalGasIronReductionPlantCostComponent
    model_inputs:
      shared_parameters:
        sponge_iron_production_rate_tonnes_per_hr: 161.8829908675799  # equivalent to 1418095 t/yr
      performance_parameters:
        water_density: 1000  # kg/m3
      cost_parameters:
        skilled_labor_cost: 40.85  # 2022 USD/hr
        unskilled_labor_cost: 30.0  # 2022 USD/hr
  sponge_iron_transport:
    performance_model:
      model: GenericTransporterPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: sponge_iron
        commodity_rate_units: kg/h
  eaf_grid_feedstock:  # electricity feedstock for EAF
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: electricity
        commodity_rate_units: kW
      performance_parameters:
        rated_capacity: 56650.  # need 56642.327357 kW
      cost_parameters:
        cost_year: 2022
        price: 0.05802  # USD/kW
        annual_cost: 0.
        start_up_cost: 0.
  eaf_water_feedstock:  # for EAF
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: water
        commodity_rate_units: galUS  # galUS/h
      performance_parameters:
        rated_capacity: 10000.  # need 9083.687924154146 galUS/h
      cost_parameters:
        cost_year: 2022
        price: 0.0016700004398318847  # cost is USD 0.441167535/t, converted to USD/gal
        annual_cost: 0.
        start_up_cost: 0.
  eaf_natural_gas_feedstock:
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: natural_gas
        commodity_rate_units: MMBtu/h
      performance_parameters:
        rated_capacity: 280.  # need 276.5242929731515 MMBtu/h
      cost_parameters:
        cost_year: 2022
        price: 4.0  # USD 4.0/MMBtu
        annual_cost: 0.
        start_up_cost: 0.
  steel_plant:
    performance_model:
      model: NaturalGasEAFPlantPerformanceComponent
    cost_model:
      model: NaturalGasEAFPlantCostComponent
    model_inputs:
      shared_parameters:
        steel_production_rate_tonnes_per_hr: 135.8187214611872  # equivalent to 1189772 t/yr
      performance_parameters:
        water_density: 1000  # kg/m3
      cost_parameters:
        skilled_labor_cost: 40.85  # 2022 USD/hr
        unskilled_labor_cost: 30.0  # 2022 USD/hr
