name: technology_config
description: This hybrid plant produces hydrogen
technologies:
  wind:
    performance_model:
      model: PYSAMWindPlantPerformanceModel
    cost_model:
      model: ATBWindPlantCostModel
    dispatch_rule_set:
      model: PyomoDispatchGenericConverter
    model_inputs:
      performance_parameters:
        num_turbines: 100
        turbine_rating_kw: 8300
        rotor_diameter: 196.
        hub_height: 130.
        create_model_from: default
        config_name: WindPowerSingleOwner
        pysam_options: !include "pysam_options_8.3MW.yaml"
        run_recalculate_power_curve: false
        layout:
          layout_mode: basicgrid
          layout_options:
            row_D_spacing: 10.0
            turbine_D_spacing: 10.0
            rotation_angle_deg: 0.0
            row_phase_offset: 0.0
            layout_shape: square
      cost_parameters:
        capex_per_kW: 1500.0
        opex_per_kW_per_year: 45
        cost_year: 2019
      dispatch_rule_parameters:
        commodity: electricity
        commodity_rate_units: kW
  battery:
    dispatch_rule_set:
      model: PyomoRuleStorageBaseclass
    control_strategy:
      model: HeuristicLoadFollowingStorageController
    performance_model:
      model: PySAMBatteryPerformanceModel
    cost_model:
      model: ATBBatteryCostModel
    model_inputs:
      shared_parameters:
        commodity: electricity
        commodity_rate_units: kW
        max_charge_rate: 100000
        max_capacity: 500000
        init_soc_fraction: 0.5
        max_soc_fraction: 0.9
        min_soc_fraction: 0.1
      performance_parameters:
        chemistry: LFPGraphite
        demand_profile: 40000  # 40 MW
      cost_parameters:
        cost_year: 2022
        energy_capex: 310  # $/kWh from 2024 ATB year 2025
        power_capex: 311  # $/kW from 2024 ATB year 2025
        opex_fraction: 0.25  # 0.25% of capex per year from 2024 ATB
      control_parameters:
        n_control_window: 24
        system_commodity_interface_limit: 1e12
  elec_combiner:
    performance_model:
      model: GenericCombinerPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: electricity
        commodity_rate_units: kW
  electrical_load_demand:
    performance_model:
      model: GenericDemandComponent
    model_inputs:
      performance_parameters:
        commodity: electricity
        commodity_rate_units: kW
        demand_profile: 50000  # 50 MW
