name: driver_config
description: This analysis runs a hybrid plant to match the first example in H2Integrate
general:
  folder_output: ex_out
driver:
  parameter_sweep:
    flag: true
    debug_print: false
    generator: csvgen
    filename: ned_reduced_sitelist.csv
    run_parallel: false
design_variables:
  site:
    latitude:
      flag: true
      units: deg
      lower: -90.0
      upper: 90.0
    longitude:
      flag: true
      units: deg
      lower: -180.0
      upper: 180.0
  dri_grid_feedstock:
    price:
      flag: true
      units: USD/MW/h
      lower: 0
      upper: 100
  hydrogen_feedstock:
    price:
      flag: true
      units: USD/kg
      lower: 0
      upper: 10
objective:
  name: finance_subgroup_sponge_iron.LCOS
recorder:
  file: cases.sql
  overwrite_recorder: true
  flag: true
  includes: [site.latitude, site.longitude, finance_subgroup_sponge_iron.LCOS]
  excludes: ['*']
