description: Driver config for CSVGen parameter sweep
name: driver_config
general:
  folder_output: ex_20_out
  create_om_reports: true
driver:
  parameter_sweep:
    flag: true
    debug_print: true
    generator: csvgen
    filename: csv_doe_cases.csv
    run_parallel: false
design_variables:
  solar:
    system_capacity_DC:
      flag: true
      lower: 5000.0
      upper: 5000000.0
      units: kW
  electrolyzer:
    n_clusters:
      flag: true
      lower: 1
      upper: 25
      units: unitless
objective:
  name: finance_subgroup_hydrogen.LCOH_optimistic
recorder:
  file: cases.sql
  overwrite_recorder: true
  flag: true
  includes: ['*']
  excludes: ['*_resource*']
