name: technology_config
description: This hybrid plant produces electricity from wind and battery storage.
technologies:
  wind:
    performance_model:
      model: PYSAMWindPlantPerformanceModel
    cost_model:
      model: ATBWindPlantCostModel
    resource:
      type: pysam_wind
      wind_speed: 9.
    model_inputs:
      performance_parameters:
        num_turbines: 25
        turbine_rating_kw: 8300
        rotor_diameter: 196.
        hub_height: 130.
        create_model_from: default
        config_name: WindPowerSingleOwner
        pysam_options: !include pysam_options_8.3MW.yaml
        run_recalculate_power_curve: false
        layout:
          layout_mode: basicgrid
          layout_options:
            row_D_spacing: 10.0
            turbine_D_spacing: 10.0
            rotation_angle_deg: 0.0
            row_phase_offset: 0.0
            layout_shape: square
      cost_parameters:
        capex_per_kW: 1500.0
        opex_per_kW_per_year: 45
        cost_year: 2019
      dispatch_rule_parameters:
        commodity: electricity
        commodity_rate_units: kW
  battery:
    control_strategy:
      model: OptimizedDispatchStorageController
    performance_model:
      model: PySAMBatteryPerformanceModel
    cost_model:
      model: ATBBatteryCostModel
    model_inputs:
      shared_parameters:
        max_charge_rate: 100000
        max_capacity: 400000
        init_soc_fraction: 0.5  # Initial SOC for the storage
        max_soc_fraction: 0.9  # Maximum SOC allowable for the storage technology
        min_soc_fraction: 0.1  # Minimum SOC allowable for the storage technology
        commodity_rate_units: kW
      performance_parameters:
        chemistry: LFPGraphite
        demand_profile: 100000  # 100 MW
      cost_parameters:
        cost_year: 2022
        energy_capex: 310  # $/kWh from 2024 ATB year 2025
        power_capex: 311  # $/kW from 2024 ATB year 2025
        opex_fraction: 0.25  # 0.25% of capex per year from 2024 ATB
      control_parameters:
        commodity: electricity
        charge_efficiency: 0.95  # Charge efficiency of the storage technology
        discharge_efficiency: 0.95  # Discharge efficiency of the storage technology
        cost_per_charge: 0.03  # in $/kW, cost to charge the storage (note that charging is incentivized)
        cost_per_discharge: 0.05  # in $/kW, cost to discharge the storage
        commodity_met_value: 0.1  # in $/kW, penalty for not meeting the desired load demand
        cost_per_production: 0.0  # in $/kW, cost to use the incoming produced commodity (i.e. electricity from wind)
        time_weighting_factor: 0.995  # This parameter discounts each subsequent time step incrementally in the future in the horizon window by this amount
        n_control_window: 24  # in timesteps (currently hours), The length of time that the control is applied to in the rolling window optimization
        system_commodity_interface_limit: 1e12
  elec_combiner:
    performance_model:
      model: GenericCombinerPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: electricity
        commodity_rate_units: kW
  electrical_load_demand:
    performance_model:
      model: GenericDemandComponent
    model_inputs:
      performance_parameters:
        commodity: electricity
        commodity_rate_units: kW
        demand_profile: 100000  # 100 MW
