name: plant_config
description: This plant is located in OR, USA
sites:
  site:
    latitude: 43.807
    longitude: -124.81
    resources:
      wind_resource:
        resource_model: WTKNLRDeveloperAPIWindResource
        resource_parameters:
          resource_year: 2010
plant:
  plant_life: 30
# array of arrays containing left-to-right technology
# interconnections; can support bidirectional connections
# with the reverse definition.
# this will naturally grow as we mature the interconnected tech
technology_interconnections:
  - [wind, electricity_splitter, electricity, cable]
  - [electricity_splitter, doc, electricity, cable]
  - [electricity_splitter, electrolyzer, electricity, cable]
resource_to_tech_connections:
  # connect the wind resource to the wind technology
  - [site.wind_resource, wind, wind_resource_data]
finance_parameters:
  finance_groups:
    finance_model: ProFastLCO
    model_inputs:
      params:
        analysis_start_year: 2032
        installation_time: 36  # months
        inflation_rate: 0.0  # 0 for real analysis
        discount_rate: 0.06  # nominal return based on 2024 ATB baseline workbook for land-based wind
        debt_equity_ratio: 0.724  # 2024 ATB uses 72.4% debt for land-based wind
        property_tax_and_insurance: 0.025  # percent of CAPEX estimated based on https://www.nlr.gov/docs/fy25osti/91775.pdf https://www.house.mn.gov/hrd/issinfo/clsrates.aspx
        total_income_tax_rate: 0.2574  # 0.257 tax rate in 2024 atb baseline workbook, value here is based on federal (21%) and state in MN (9.8)
        capital_gains_tax_rate: 0.15  # H2FAST default
        sales_tax_rate: 0.0  # average combined state and local sales tax https://taxfoundation.org/location/texas/
        debt_interest_rate: 0.07  # based on 2024 ATB nominal interest rate for land-based wind
        debt_type: Revolving debt  # can be "Revolving debt" or "One time loan". Revolving debt is H2FAST default and leads to much lower LCOH
        loan_period_if_used: 0  # H2FAST default, not used for revolving debt
        cash_onhand_months: 1  # H2FAST default
        admin_expense: 0.00  # percent of sales H2FAST default
      capital_items:
        depr_type: MACRS   # can be "MACRS" or "Straight line"
        depr_period: 7  # 5  years - for clean energy facilities as specified by the IRS MACRS schedule https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
        refurb: [0.]
  cost_adjustment_parameters:
    cost_year_adjustment_inflation: 0.025  # used to adjust modeled costs to target_dollar_year
    target_dollar_year: 2022
  finance_subgroups:
    electricity:
      commodity: electricity
      technologies: [wind]
    hydrogen:
      commodity: hydrogen
      technologies: [wind, electrolyzer]
    co2:
      commodity: co2
      technologies: [wind, doc]
