name: technology_config
description: This hybrid plant produces hydrogen
technologies:
  wind:
    performance_model:
      model: PYSAMWindPlantPerformanceModel
    cost_model:
      model: ATBWindPlantCostModel
    model_inputs:
      performance_parameters:
        num_turbines: 100
        turbine_rating_kw: 8300
        rotor_diameter: 196.
        hub_height: 130.
        create_model_from: default
        config_name: WindPowerSingleOwner
        pysam_options: !include "pysam_options_8.3MW.yaml"
        run_recalculate_power_curve: false
        layout:
          layout_mode: basicgrid
          layout_options:
            row_D_spacing: 10.0
            turbine_D_spacing: 10.0
            rotation_angle_deg: 0.0
            row_phase_offset: 0.0
            layout_shape: square
      cost_parameters:
        capex_per_kW: 1500.0
        opex_per_kW_per_year: 45
        cost_year: 2019
  electrolyzer:
    performance_model:
      model: ECOElectrolyzerPerformanceModel
    cost_model:
      model: SingliticoCostModel
    model_inputs:
      shared_parameters:
        location: onshore
        electrolyzer_capex: 1295  # $/kW overnight installed capital costs for a 1 MW system in 2022 USD/kW (DOE hydrogen program record 24005 Clean Hydrogen Production Cost Scenarios with PEM Electrolyzer Technology 05/20/24) (https://www.hydrogen.energy.gov/docs/hydrogenprogramlibraries/pdfs/24005-clean-hydrogen-production-cost-pem-electrolyzer.pdf?sfvrsn=8cb10889_1)
      performance_parameters:
        size_mode: normal
        n_clusters: 18
        cluster_rating_MW: 40
        eol_eff_percent_loss: 13  # eol defined as x% change in efficiency from bol
        uptime_hours_until_eol: 80000.  # number of 'on' hours until electrolyzer reaches eol
        include_degradation_penalty: true  # include degradation
        turndown_ratio: 0.1  # turndown_ratio = minimum_cluster_power/cluster_rating_MW
      financial_parameters:
        capital_items:
          depr_period: 7  # based on PEM Electrolysis H2A Production Case Study Documentation estimate of 7 years. also see https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
          replacement_cost_percent: 0.15  # percent of capex - H2A default case
  h2_storage:
    performance_model:
      model: StoragePerformanceModel
    cost_model:
      model: LinedRockCavernStorageCostModel
    control_strategy:
      model: DemandOpenLoopStorageController
    model_inputs:
      shared_parameters:
        commodity: hydrogen
        commodity_rate_units: kg/h
        max_charge_rate: 12446.00729773  # kg/time step
        max_capacity: 2987042.0  # kg
        max_soc_fraction: 1.0  # fraction (0-1)
        min_soc_fraction: 0.1  # fraction (0-1)
        init_soc_fraction: 0.25  # fraction (0-1)
        max_discharge_rate: 12446.00729773  # kg/time step
        charge_efficiency: 1.0  # fraction (0-1)
        discharge_efficiency: 1.0  # fraction (0-1)
        demand_profile: 5000  # constant demand of 5000 kg per hour (see commodity_rate_units)
  h2_combiner:
    performance_model:
      model: GenericCombinerPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: hydrogen
        commodity_rate_units: kg/h
  h2_load_demand:
    performance_model:
      model: GenericDemandComponent
    model_inputs:
      performance_parameters:
        commodity: hydrogen
        commodity_rate_units: kg/h
        demand_profile: 5000  # 5000 kg/h
