name: technology_config
description: This hybrid plant produces ammonia
technologies:
  electrolyzer:
    performance_model:
      model: ECOElectrolyzerPerformanceModel
    cost_model:
      model: SingliticoCostModel
    model_inputs:
      shared_parameters:
        location: onshore
        electrolyzer_capex: 1295  # $/kW overnight installed capital costs for a 1 MW system in 2022 USD/kW (DOE hydrogen program record 24005	Clean Hydrogen Production Cost Scenarios with PEM Electrolyzer Technology 05/20/24) (https://www.hydrogen.energy.gov/docs/hydrogenprogramlibraries/pdfs/24005-clean-hydrogen-production-cost-pem-electrolyzer.pdf?sfvrsn=8cb10889_1)
      performance_parameters:
        size_mode: normal
        n_clusters: 16
        cluster_rating_MW: 40
        pem_control_type: basic
        eol_eff_percent_loss: 10  # eol defined as x% change in efficiency from bol
        uptime_hours_until_eol: 80000  # number of 'on' hours until electrolyzer reaches eol
        include_degradation_penalty: true  # include degradation
        turndown_ratio: 0.1  # turndown_ratio = minimum_cluster_power/cluster_rating_MW
      financial_parameters:
        capital_items:
          depr_period: 7  # based on PEM Electrolysis H2A Production Case Study Documentation estimate of 7 years. also see https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
          replacement_cost_percent: 0.15  # percent of capex - H2A default case
  electricity_feedstock:
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: electricity
        commodity_rate_units: MW
      performance_parameters:
        rated_capacity: 1048.0
      cost_parameters:
        cost_year: 2022
        price: 0.0
        annual_cost: 0.0
        start_up_cost: 0.0
  electricity_splitter:
    performance_model:
      model: GenericSplitterPerformanceModel
    model_inputs:
      performance_parameters:
        split_mode: fraction
        commodity: electricity
        commodity_rate_units: MW
        fraction_to_priority_tech: 0.99
  n2_feedstock:
    performance_model:
      model: FeedstockPerformanceModel
    cost_model:
      model: FeedstockCostModel
    model_inputs:
      shared_parameters:
        commodity: nitrogen
        commodity_rate_units: t/h
      performance_parameters:
        rated_capacity: 50.0  # metric tonnes of N2/hour
      cost_parameters:
        cost_year: 2022
        price: 0.0
        annual_cost: 0.
        start_up_cost: 0.0
  ammonia:
    performance_model:
      model: AmmoniaSynLoopPerformanceModel
    cost_model:
      model: AmmoniaSynLoopCostModel
    model_inputs:  # See converters/ammonia/Ammonia cost breakdown-ANL source.xlsx
      shared_parameters:
        production_capacity: 52777.6
        catalyst_consumption_rate: 0.000091295354067341
        catalyst_replacement_interval: 3
      performance_parameters:
        size_mode: normal
        capacity_factor: 0.9
        energy_demand: 0.530645243
        heat_output: 0.8299956
        feed_gas_t: 25.8
        feed_gas_p: 20
        feed_gas_x_n2: 0.25
        feed_gas_x_h2: 0.75
        feed_gas_mass_ratio: 1.13
        purge_gas_t: 7.5
        purge_gas_p: 275
        purge_gas_x_n2: 0.26
        purge_gas_x_h2: 0.68
        purge_gas_x_ar: 0.02
        purge_gas_x_nh3: 0.04
        purge_gas_mass_ratio: 0.07
      cost_parameters:
        baseline_capacity: 52777.6
        base_cost_year: 2016
        capex_scaling_exponent: 0.6
        labor_scaling_exponent: 0.25
        asu_capex_base: 236920646  # See ASU + HB capex-NETL source.xlsx
        synloop_capex_base: 302460908  # See ASU + HB capex-NETL source.xlsx
        heat_capex_base: 7069100
        cool_capex_base: 4799200
        other_eqpt_capex_base: 0.001
        land_capex_base: 4112701.84103543
        deprec_noneq_capex_rate: 0.42
        labor_rate_base: 57
        num_workers_base: 50
        hours_yr: 2080
        gen_admin: 0.2
        prop_tax_ins: 0.02
        maint_rep: 0.005
        oxygen_byproduct_rate: 0.29405077250145
        water_consumption_rate: 0.049236824
        rebuild_cost_base: 0.001
        cooling_water_cost_base: 0.000113349938601175
        catalyst_cost_base: 23.19977341
        oxygen_price_base: 0.0285210891617726
