name: plant_config
description: This plant is located in MN, USA...
sites:
  site:
    latitude: 32.31714
    longitude: -100.18
    resources:
      wind_resource:
        resource_model: WTKNLRDeveloperAPIWindResource
        resource_parameters:
          resource_year: 2013
      solar_resource:
        resource_model: GOESAggregatedSolarAPI
        resource_parameters:
          resource_year: 2013
# array of arrays containing left-to-right technology
# interconnections; can support bidirectional connections
# with the reverse definition.
# this will naturally grow as we mature the interconnected tech
technology_interconnections:
  - [wind, combiner, electricity, cable]
  - [solar, combiner, electricity, cable]
  - [combiner, battery, electricity, cable]
  # combine the battery output with the wind and solar generation
  - [battery, elec_combiner, electricity, cable]
  - [combiner, elec_combiner, electricity, cable]
  # connect the electricity supply to the electrolyzer
  - [elec_combiner, electrolyzer, electricity, cable]
  - [electrolyzer, h2_storage, hydrogen, pipe]
  # combine the h2 from the electrolyzer and the h2_storage
  - [electrolyzer, h2_combiner, hydrogen, pipe]
  - [h2_storage, h2_combiner, hydrogen, pipe]
  # connect the hydrogen supply to the ammonia model
  - [h2_combiner, ammonia, hydrogen, pipe]
  - [finance_subgroup_hydrogen, ammonia, LCOH]
  # etc
tech_to_dispatch_connections:
  - [combiner, battery]
  - [battery, battery]
resource_to_tech_connections:
  # connect the wind resource to the wind technology
  - [site.wind_resource, wind, wind_resource_data]
  - [site.solar_resource, solar, solar_resource_data]
plant:
  plant_life: 30
finance_parameters:
  finance_groups:
    finance_model: ProFastLCO
    model_inputs:
      save_profast_config: true
      save_profast_results: false
      profast_output_description: profast_output
      params:
        analysis_start_year: 2032
        installation_time: 36  # months
        inflation_rate: 0.0  # 0 for real analysis
        discount_rate: 0.06  # nominal return based on 2024 ATB baseline workbook for land-based wind
        debt_equity_ratio: 0.724  # 2024 ATB uses 72.4% debt for land-based wind
        property_tax_and_insurance: 0.025 # https://www.house.mn.gov/hrd/issinfo/clsrates.aspx and  # percent of CAPEX estimated based on https://www.nlr.gov/docs/fy25osti/91775.pdf
        total_income_tax_rate: 0.2574  # 0.257 tax rate in 2024 atb baseline workbook, value here is based on federal (21%) and state in MN (9.8)
        capital_gains_tax_rate: 0.15  # H2FAST default
        sales_tax_rate: 0.0  # average combined state and local sales tax https://taxfoundation.org/location/texas/
        debt_interest_rate: 0.07  # based on 2024 ATB nominal interest rate for land-based wind
        debt_type: Revolving debt  # can be "Revolving debt" or "One time loan". Revolving debt is H2FAST default and leads to much lower LCOH
        loan_period_if_used: 0  # H2FAST default, not used for revolving debt
        cash_onhand_months: 1  # H2FAST default
        admin_expense: 0.00  # percent of sales H2FAST default
      capital_items:
        depr_type: MACRS   # can be "MACRS" or "Straight line"
        depr_period: 7  # years - for clean energy facilities as specified by the IRS MACRS schedule https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
        refurb: [0.]
  cost_adjustment_parameters:
    cost_year_adjustment_inflation: 0.025  # used to adjust modeled costs to target_dollar_year
    target_dollar_year: 2022
  finance_subgroups:
    electricity:
      commodity: electricity
      commodity_stream: combiner
      technologies: [wind, solar, battery]
    hydrogen:
      commodity: hydrogen
      technologies: [wind, solar, battery, electrolyzer, h2_storage]
    ammonia:
      commodity: ammonia
      technologies:
        - wind
        - solar
        - battery
        - electrolyzer
        - h2_storage
        - ammonia
