name: technology_config
description: This hybrid plant produces ammonia
technologies:
  wind:
    performance_model:
      model: FlorisWindPlantPerformanceModel
    cost_model:
      model: ATBWindPlantCostModel
    model_inputs:
      performance_parameters:
        num_turbines: 148  # number of turbines in the farm
        hub_height: 115.0  # turbine hub-height
        operational_losses: 10.49  # percentage of non-wake losses
        floris_wake_config: !include "floris_v4_default_template.yaml" #floris wake model file
        floris_turbine_config: !include "floris_turbine_NREL_6MW_170.yaml" #turbine model file formatted for floris
        resource_data_averaging_method: average   #"weighted_average", "average" or "nearest"
        operation_model: cosine-loss  # turbine operation model
        default_turbulence_intensity: 0.06
        enable_caching: true  # whether to use cached results
        cache_dir: cache  # directory to save or load cached data
        layout:
          layout_mode: basicgrid
          layout_options:
            row_D_spacing: 7.0
            turbine_D_spacing: 7.0
            rotation_angle_deg: 0.0
            row_phase_offset: 0.0
            layout_shape: square
      cost_parameters:
        capex_per_kW: 1380.0
        opex_per_kW_per_year: 29.0
        cost_year: 2019
  solar:
    performance_model:
      model: PYSAMSolarPlantPerformanceModel
    cost_model:
      model: ATBResComPVCostModel
    model_inputs:
      shared_parameters:
        pv_capacity_kWdc: 400000  # 400 MWdc
      performance_parameters:
        dc_ac_ratio: 1.3
        create_model_from: default
        config_name: PVWattsSingleOwner
        tilt_angle_func: lat-func
        pysam_options:
          SystemDesign:
            inv_eff: 96.0
            module_type: 0  # 19% efficiency
            losses: 14.08  # dc losses
          Lifetime:
            dc_degradation: [0]
      cost_parameters:
        capex_per_kWdc: 1323
        opex_per_kWdc_per_year: 18
        cost_year: 2019
  combiner:
    performance_model:
      model: GenericCombinerPerformanceModel
    dispatch_rule_set:
      model: PyomoDispatchGenericConverter
    model_inputs:
      shared_parameters:
        commodity: electricity
        commodity_rate_units: kW
  battery:
    dispatch_rule_set:
      model: PyomoRuleStorageBaseclass
    control_strategy:
      model: HeuristicLoadFollowingStorageController
    performance_model:
      model: PySAMBatteryPerformanceModel
    cost_model:
      model: ATBBatteryCostModel
    model_inputs:
      shared_parameters:
        commodity: electricity
        commodity_rate_units: kW
        max_charge_rate: 96.0  # kW
        max_capacity: 96.0  # kWh
        init_soc_fraction: 0.9
        max_soc_fraction: 1.0
        min_soc_fraction: 0.2
      performance_parameters:
        chemistry: LFPGraphite
        demand_profile: 640000  # 640 MW
      cost_parameters:
        cost_year: 2019
        energy_capex: 310  # $/kWh from 2024 ATB year 2025
        power_capex: 311  # $/kW from 2024 ATB year 2025
        opex_fraction: 0.025
      control_parameters:
        system_commodity_interface_limit: 1e12
        n_control_window: 24
  elec_combiner:
    performance_model:
      model: GenericCombinerPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: electricity
        commodity_rate_units: kW
  electrolyzer:
    performance_model:
      model: ECOElectrolyzerPerformanceModel
    cost_model:
      model: SingliticoCostModel
    model_inputs:
      shared_parameters:
        location: onshore
        electrolyzer_capex: 1295  # $/kW overnight installed capital costs for a 1 MW system in 2022 USD/kW (DOE hydrogen program record 24005	Clean Hydrogen Production Cost Scenarios with PEM Electrolyzer Technology 05/20/24) (https://www.hydrogen.energy.gov/docs/hydrogenprogramlibraries/pdfs/24005-clean-hydrogen-production-cost-pem-electrolyzer.pdf?sfvrsn=8cb10889_1)
      performance_parameters:
        size_mode: normal
        n_clusters: 16
        cluster_rating_MW: 40
        eol_eff_percent_loss: 10  # eol defined as x% change in efficiency from bol
        uptime_hours_until_eol: 80000  # number of 'on' hours until electrolyzer reaches eol
        include_degradation_penalty: true  # include degradation
        turndown_ratio: 0.1  # turndown_ratio = minimum_cluster_power/cluster_rating_MW
      financial_parameters:
        capital_items:
          depr_period: 7  # based on PEM Electrolysis H2A Production Case Study Documentation estimate of 7 years. also see https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
          replacement_cost_percent: 0.15  # percent of capex - H2A default case
  h2_storage:
    performance_model:
      model: StorageAutoSizingModel
    control_strategy:
      model: SimpleStorageOpenLoopController
    cost_model:
      model: SaltCavernStorageCostModel
    model_inputs:
      shared_parameters:
        commodity: hydrogen
        commodity_rate_units: kg/h
        commodity_amount_units: kg
        set_demand_as_avg_commodity_in: true
      performance_parameters:
        min_soc_fraction: 0.0
        max_soc_fraction: 1.0
        charge_efficiency: 1.0
        discharge_efficiency: 1.0
      cost_parameters:
        # since the storage is being auto-sized by the performance model,
        # we set the sizing mode to 'auto' rather than defining the capacities
        # in the input file
        sizing_mode: auto  # set as "auto" so storage capacity doesnt have to be defined
  h2_combiner:
    performance_model:
      model: GenericCombinerPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: hydrogen
        commodity_rate_units: kg/h
  ammonia:
    performance_model:
      model: SimpleAmmoniaPerformanceModel
    cost_model:
      model: SimpleAmmoniaCostModel
    model_inputs:
      shared_parameters:
        plant_capacity_factor: 0.9
        plant_capacity_kgpy: 362560000.
      cost_parameters:
        electricity_cost: 91  # 2022 USD - not actually used in cost/finance model
        # hydrogen_cost: 4.023963541079105
        cooling_water_cost: 0.00516275276753 #  # 2022 USD/gal
        iron_based_catalyst_cost: 25  # 2022 USD/kg
        oxygen_cost: 0
        electricity_consumption: 0.0001207
        hydrogen_consumption: 0.197284403
        cooling_water_consumption: 0.049236824
        iron_based_catalyst_consumption: 0.000091295354067341
        oxygen_byproduct: 0.29405077250145
        capex_scaling_exponent: 0.6
