name: plant_config
description: Demonstrates multivariable streams with a gas combiner
plant:
  plant_life: 30
  simulation:
    n_timesteps: 8760
    dt: 3600
    timezone: -6
technology_interconnections:
  - [gas_producer_1, gas_combiner, wellhead_gas_mixture]
  - [gas_producer_2, gas_combiner, wellhead_gas_mixture]
  - [gas_combiner, gas_consumer, wellhead_gas_mixture]
