"""Auto-generate the model registry section of ``docs/user_guide/model_overview.md``.

This script discovers every model that is registered in
:data:`h2integrate.core.supported_models.supported_models`, classifies each one
by category (resource, converter, transport, storage, control, etc.) and role
(performance, cost, financial, controller, ...), and rewrites the block
delimited by ``BEGIN_AUTOGENERATED`` / ``END_AUTOGENERATED`` markers in
``docs/user_guide/model_overview.md``.

The script is invoked from ``docs/build_book.sh`` before Jupyter Book runs so
that the docs are always in sync with the registry. It can also be run
manually:

.. code-block:: bash

    python docs/generate_model_overview.py

If a registered model fails to import, a warning is printed and the model is
listed without role information so the build still succeeds.
"""

from __future__ import annotations

import re
import sys
import inspect
import warnings
from pathlib import Path
from collections import defaultdict
from dataclasses import dataclass

from h2integrate.core.supported_models import supported_models


# ---------------------------------------------------------------------------
# Markers used in ``model_overview.md`` to delimit the generated block.
# Everything between (and not including) these two lines is replaced on every
# run.  Outside-the-block content (the human-edited intro) is preserved.
# ---------------------------------------------------------------------------
BEGIN_MARKER = "<!-- BEGIN_AUTOGENERATED_MODEL_REGISTRY -->"
END_MARKER = "<!-- END_AUTOGENERATED_MODEL_REGISTRY -->"


# ---------------------------------------------------------------------------
# Top-level category mapping.
#
# Each entry maps the leading segment of a model class' dotted module path
# (relative to the ``h2integrate`` package) to:
#   - a stable section anchor (used for cross-references)
#   - a human-readable heading
#   - the order the category should appear in the rendered overview
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class CategorySpec:
    anchor: str
    heading: str
    order: int


CATEGORIES: dict[str, CategorySpec] = {
    "resource": CategorySpec("resource-models", "Resource models", 1),
    "converters": CategorySpec("converter-models", "Converter models", 2),
    "transporters": CategorySpec("transport-models", "Transport models", 3),
    "storage": CategorySpec("storage-models", "Storage models", 4),
    "control": CategorySpec("control-models", "Control models", 5),
    "demand": CategorySpec("demand-models", "Demand models", 6),
    "feedstocks": CategorySpec("feedstock-models", "Feedstock models", 7),
    "finances": CategorySpec("finance-models", "Finance models", 8),
}


# ---------------------------------------------------------------------------
# Friendly labels for the second-level grouping inside each category.
#
# Keyed by the full dotted module path of the *subpackage* the class lives in.
# Anything that is not in this map falls back to the bare subpackage name.
# Add an entry here when you want a nicer label or a one-line description in
# the rendered docs.
# ---------------------------------------------------------------------------
SUBCATEGORY_LABELS: dict[str, tuple[str, str]] = {
    # (display name, short description)
    # ---- Resources ----
    "h2integrate.resource.wind": ("wind", "wind resource data providers"),
    "h2integrate.resource.solar": ("solar", "solar resource data providers"),
    "h2integrate.resource.tidal": ("tidal", "tidal resource data providers"),
    "h2integrate.resource.wave": ("wave", "wave resource data providers"),
    "h2integrate.resource.river": ("river", "river resource data providers"),
    # ---- Converters ----
    "h2integrate.converters": ("generic", "generic converter components"),
    "h2integrate.converters.wind": ("wind", "wind turbine plants"),
    "h2integrate.converters.solar": ("solar", "solar-PV panels"),
    "h2integrate.converters.water_power": (
        "water_power",
        "wave, tidal, and run-of-river hydropower",
    ),
    "h2integrate.converters.hydrogen": ("hydrogen", "hydrogen production"),
    "h2integrate.converters.hydrogen.geologic": (
        "geoh2",
        "geologic hydrogen well and surface processing",
    ),
    "h2integrate.converters.nitrogen": ("nitrogen", "nitrogen separation from air"),
    "h2integrate.converters.iron": ("iron", "iron mining, reduction, and electrowinning"),
    "h2integrate.converters.steel": ("steel", "steel production"),
    "h2integrate.converters.ammonia": ("ammonia", "ammonia synthesis"),
    "h2integrate.converters.methanol": ("methanol", "methanol synthesis"),
    "h2integrate.converters.co2.marine": ("co2_marine", "marine carbon dioxide removal"),
    "h2integrate.converters.natural_gas": (
        "natural_gas",
        "natural gas combined-cycle and combustion turbines",
    ),
    "h2integrate.converters.nuclear": ("nuclear", "nuclear power plants"),
    "h2integrate.converters.grid": ("grid", "electricity grid connection"),
    "h2integrate.converters.water.desal": ("desal", "water desalination"),
    # ---- Transport ----
    "h2integrate.transporters": ("transport", "commodity transporters, combiners, and splitters"),
    # ---- Storage ----
    "h2integrate.storage": ("generic_storage", "generic storage performance/cost"),
    "h2integrate.storage.battery": ("battery", "battery storage"),
    "h2integrate.storage.hydrogen": ("h2_storage", "hydrogen storage"),
    # ---- Control ----
    "h2integrate.control.control_strategies.storage": (
        "storage_controllers",
        "storage controllers",
    ),
    "h2integrate.control.control_strategies.system_level": (
        "system_level_controllers",
        "system-level controllers",
    ),
    "h2integrate.control.control_rules.converters": (
        "pyomo_converter_dispatch",
        "Pyomo dispatch rules for converters",
    ),
    "h2integrate.control.control_rules.storage": (
        "pyomo_storage_dispatch",
        "Pyomo dispatch rules for storage",
    ),
    # ---- Other ----
    "h2integrate.demand": ("demand", "demand components"),
    "h2integrate.feedstocks": ("feedstocks", "feedstock supply"),
    "h2integrate.finances": ("finances", "finance models (LCO/NPV)"),
}


# ---------------------------------------------------------------------------
# Models that combine multiple roles (performance + cost, or cost + finance).
# The class is rendered under both bullets in its subcategory.
# ---------------------------------------------------------------------------
COMBINED_PERFORMANCE_AND_COST_MODELS: frozenset[str] = frozenset(
    {
        "WOMBATElectrolyzerModel",
    }
)

COMBINED_COST_AND_FINANCIAL_MODELS: frozenset[str] = frozenset(
    {
        "SteelCostAndFinancialModel",
        "OAECostAndFinancialModel",
    }
)


# ---------------------------------------------------------------------------
# Models intentionally excluded from the public overview.
#
# Currently this is limited to the dummy components used by multivariable
# stream tests/demos.  Add or remove entries here to control visibility.
# ---------------------------------------------------------------------------
HIDDEN_MODELS: frozenset[str] = frozenset(
    {
        "SimpleGasProducerPerformance",
        "SimpleGasProducerCost",
        "SimpleGasConsumerPerformance",
        "SimpleGasConsumerCost",
    }
)


# ---------------------------------------------------------------------------
# Stable order of role bullets within each subcategory.
# ---------------------------------------------------------------------------
ROLE_ORDER: tuple[str, ...] = (
    "performance",
    "cost",
    "combined_performance_and_cost",
    "combined_cost_and_financial",
    "financial",
    "controller",
    "dispatch_rule",
    "other",
)

ROLE_LABELS: dict[str, str] = {
    "performance": "performance models",
    "cost": "cost models",
    "combined_performance_and_cost": "combined performance and cost models",
    "combined_cost_and_financial": "combined cost and financial models",
    "financial": "financial models",
    "controller": "controllers",
    "dispatch_rule": "dispatch rules",
    "other": "other components",
}


# ---------------------------------------------------------------------------
# Classification logic
# ---------------------------------------------------------------------------


def _classify_role(class_name: str, cls: type) -> str:
    """Determine which role bullet a model class should appear under.

    The classification looks at the MRO (so a model that inherits any of the
    base classes registered below is picked up automatically) plus a small
    set of explicit overrides for models that combine multiple roles. As a
    final fallback, a class whose name ends with ``FinanceModel`` or
    ``FinancialModel`` is classified as ``financial`` (used for technology
    finance wrappers that do not share a common base class).
    """
    if class_name in COMBINED_PERFORMANCE_AND_COST_MODELS:
        return "combined_performance_and_cost"
    if class_name in COMBINED_COST_AND_FINANCIAL_MODELS:
        return "combined_cost_and_financial"

    mro_names = {base.__name__ for base in cls.__mro__}

    if "CostModelBaseClass" in mro_names:
        return "cost"
    if "ProFastBase" in mro_names or cls.__module__.startswith("h2integrate.finances"):
        return "financial"
    if "PyomoRuleBaseClass" in mro_names or cls.__module__.startswith(
        "h2integrate.control.control_rules"
    ):
        return "dispatch_rule"
    if cls.__module__.startswith("h2integrate.control.control_strategies"):
        return "controller"
    if "PerformanceModelBaseClass" in mro_names:
        return "performance"
    if cls.__name__.endswith(("FinanceModel", "FinancialModel")):
        return "financial"
    return "other"


def _category_for_module(module_path: str) -> str | None:
    """Map a dotted module path to one of the top-level categories."""
    if not module_path.startswith("h2integrate."):
        return None
    # h2integrate.<top>.<...>
    parts = module_path.split(".")
    if len(parts) < 2:
        return None
    top = parts[1]
    return top if top in CATEGORIES else None


def _subcategory_for_module(module_path: str) -> tuple[str, str, str]:
    """Resolve the (subpackage key, label, description) for a class' module.

    Looks for the longest match in :data:`SUBCATEGORY_LABELS`. Falls back to
    the immediate subpackage name (with no description) if no entry matches.
    """
    parts = module_path.split(".")
    # Walk from the most specific subpackage down to the least specific.
    for depth in range(len(parts) - 1, 1, -1):
        candidate = ".".join(parts[:depth])
        if candidate in SUBCATEGORY_LABELS:
            label, desc = SUBCATEGORY_LABELS[candidate]
            return candidate, label, desc

    # Fallback: use the second-from-top segment (e.g. "wind" from
    # ``h2integrate.converters.wind.wind_pysam``).  No description.
    if len(parts) >= 3:
        return ".".join(parts[:3]), parts[2], ""
    return module_path, parts[-1], ""


# ---------------------------------------------------------------------------
# Data collection
# ---------------------------------------------------------------------------


@dataclass
class ModelEntry:
    class_name: str  # The key under which the class is registered.
    actual_name: str  # ``cls.__name__`` -- may differ from class_name (e.g. ``cable``).
    module_path: str
    role: str
    subcat_key: str
    subcat_label: str
    subcat_desc: str
    summary: str  # First sentence of the class docstring; ``""`` if absent.


# Regex used to split off the first sentence of a docstring.  Matches a
# sentence terminator (``.``, ``!``, or ``?``) followed by whitespace.  We
# explicitly avoid splitting on ``e.g.``, ``i.e.``, ``etc.``, etc.
_SENTENCE_SPLIT_RE = re.compile(r"(?<!\b[A-Za-z])(?<=[.!?])\s+")

_ABBREVIATIONS = ("e.g.", "i.e.", "etc.", "vs.", "cf.", "Inc.", "Ltd.")


def _first_sentence_of_docstring(cls: type) -> str:
    """Return the first sentence of ``cls``'s own docstring, or ``""``.

    We deliberately ignore inherited docstrings here: a class without its own
    ``__doc__`` should render with no summary so the gap is visible (and so
    we don't surface unhelpful "Baseclass to be used for all cost models"
    strings for every uncommented subclass). The summary paragraph is
    collapsed onto a single line and truncated at the first sentence
    terminator that isn't part of a common abbreviation.
    """
    raw = cls.__dict__.get("__doc__")
    if not raw:
        return ""
    raw = inspect.cleandoc(raw)
    if not raw:
        return ""

    # Take only the leading paragraph (the conventional "summary line").
    paragraph = raw.split("\n\n", 1)[0].strip()
    if not paragraph:
        return ""
    # Collapse internal whitespace so the rendered bullet stays on one line.
    paragraph = " ".join(paragraph.split())

    # Walk forward and stop at the first sentence terminator that isn't part
    # of a known abbreviation.
    for match in re.finditer(r"[.!?]", paragraph):
        end = match.end()
        head = paragraph[:end]
        if any(head.endswith(abbr) for abbr in _ABBREVIATIONS):
            continue
        if end == len(paragraph) or paragraph[end].isspace():
            return head.strip()

    return paragraph


def collect_models() -> dict[str, dict[str, list[ModelEntry]]]:
    """Walk the registry and group classes by ``category -> subcategory_key``.

    Each subcategory bucket is a list of :class:`ModelEntry` instances, sorted
    by class name and then by role.
    """
    grouped: dict[str, dict[str, list[ModelEntry]]] = defaultdict(lambda: defaultdict(list))

    for class_name in sorted(supported_models.keys()):
        if class_name in HIDDEN_MODELS:
            continue
        try:
            cls = supported_models[class_name]
        except Exception as exc:  # noqa: BLE001 - lazy imports may raise anything; we warn and skip
            warnings.warn(
                f"Could not import model {class_name!r}: {exc}. "
                "It will be omitted from the auto-generated overview.",
                stacklevel=2,
            )
            continue

        module_path = cls.__module__
        category = _category_for_module(module_path)
        if category is None:
            # Skip anything we can't categorize (currently nothing).
            continue

        subcat_key, subcat_label, subcat_desc = _subcategory_for_module(module_path)
        role = _classify_role(class_name, cls)

        grouped[category][subcat_key].append(
            ModelEntry(
                class_name=class_name,
                actual_name=cls.__name__,
                module_path=module_path,
                role=role,
                subcat_key=subcat_key,
                subcat_label=subcat_label,
                subcat_desc=subcat_desc,
                summary=_first_sentence_of_docstring(cls),
            )
        )

    return grouped


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------


def _role_sort_key(entry: ModelEntry) -> tuple[int, str]:
    try:
        idx = ROLE_ORDER.index(entry.role)
    except ValueError:
        idx = len(ROLE_ORDER)
    return (idx, entry.class_name)


def _render_class_link(entry: ModelEntry) -> str:
    """Render a class as a cross-reference to its autodoc entry.

    Uses the MyST ``{py:class}`` role so the link resolves to the page that
    ``autosummary`` generates for the class. The leading ``~`` makes the
    rendered link text just the class name (no module prefix). If the class
    has a docstring, its first sentence is appended after a hyphen to give
    the bullet some context at a glance.

    When the registry key differs from the actual class name (e.g. the
    transport ``cable`` / ``pipe`` aliases), the registry key is shown
    alongside the class link so users can find both in the YAML and in code.
    """
    link = f"{{py:class}}`~{entry.module_path}.{entry.actual_name}`"
    if entry.class_name != entry.actual_name:
        link = f"{link} (registered as `{entry.class_name}`)"
    if entry.summary:
        return f"{link} - {entry.summary}"
    return link


def render_category(category: str, subcats: dict[str, list[ModelEntry]]) -> str:
    """Render the markdown for a single top-level category."""
    spec = CATEGORIES[category]
    lines: list[str] = []
    lines.append(f"({spec.anchor})=")
    lines.append(f"## {spec.heading}")
    lines.append("")

    # Sort subcategories by label so the rendered output is stable and
    # alphabetical within each category.
    def _subcat_sort_key(item: tuple[str, list[ModelEntry]]) -> str:
        entries = item[1]
        return entries[0].subcat_label if entries else item[0]

    for _subcat_key, entries in sorted(subcats.items(), key=_subcat_sort_key):
        if not entries:
            continue
        label = entries[0].subcat_label
        desc = entries[0].subcat_desc
        header = f"- `{label}`" + (f": {desc}" if desc else "")
        lines.append(header)

        # Group entries within this subcategory by role, preserving role order.
        by_role: dict[str, list[ModelEntry]] = defaultdict(list)
        for entry in entries:
            by_role[entry.role].append(entry)

        for role in ROLE_ORDER:
            role_entries = by_role.get(role)
            if not role_entries:
                continue
            lines.append(f"  - {ROLE_LABELS[role]}:")
            lines.extend(
                f"    + {_render_class_link(entry)}"
                for entry in sorted(role_entries, key=_role_sort_key)
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_overview(grouped: dict[str, dict[str, list[ModelEntry]]]) -> str:
    """Render the full auto-generated block (between marker comments)."""
    intro = (
        "<!--\n"
        "    THIS BLOCK IS AUTO-GENERATED by ``docs/generate_model_overview.py``.\n"
        "    Do not edit by hand. To add or rename a model, update the registry in\n"
        "    ``h2integrate/core/supported_models.py``. To change a subcategory\n"
        "    label or description, edit ``SUBCATEGORY_LABELS`` in the generator.\n"
        "-->\n\n"
        "(technology-models-overview)=\n"
        "# Technology Models Overview\n\n"
        "The tables below are generated at docs build time from\n"
        "[`supported_models.py`](../../h2integrate/core/supported_models.py)\n"
        "and the package source tree, so they always reflect the models that\n"
        "are actually registered with H2Integrate. Each class name links to its\n"
        "auto-generated API page.\n\n"
    )

    sections = []
    for category, _spec in sorted(CATEGORIES.items(), key=lambda kv: kv[1].order):
        subcats = grouped.get(category)
        if not subcats:
            continue
        sections.append(render_category(category, subcats))

    return intro + "\n".join(sections)


# ---------------------------------------------------------------------------
# File-level rewriting
# ---------------------------------------------------------------------------


def rewrite_overview(target: Path, generated_block: str) -> None:
    """Replace the block between the marker comments in ``target``.

    Raises ``RuntimeError`` if the markers are missing or out of order so that
    the docs build fails loudly rather than silently producing stale content.
    """
    original = target.read_text(encoding="utf-8")
    begin = original.find(BEGIN_MARKER)
    end = original.find(END_MARKER)
    if begin < 0 or end < 0 or end < begin:
        raise RuntimeError(
            f"Could not find marker pair '{BEGIN_MARKER}' .. '{END_MARKER}' "
            f"in {target}. Add the markers to delimit the auto-generated section."
        )

    before = original[: begin + len(BEGIN_MARKER)]
    after = original[end:]
    new_content = f"{before}\n{generated_block}\n{after}"
    if new_content != original:
        target.write_text(new_content, encoding="utf-8")


def main() -> int:
    target = Path(__file__).resolve().parent / "user_guide" / "model_overview.md"
    if not target.exists():
        print(f"ERROR: target file does not exist: {target}", file=sys.stderr)
        return 1

    grouped = collect_models()
    block = render_overview(grouped)
    rewrite_overview(target, block)
    n_models = sum(len(entries) for subs in grouped.values() for entries in subs.values())
    print(f"Updated {target.relative_to(target.parents[2])} with {n_models} models.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
