name: plant_config
description: Simulation for Peak Load Management MILP-optimized battery dispatch
plant:
  plant_life: 1
  simulation:
    n_timesteps: 8760  # full year (hourly)
    dt: 3600  # 1-hour timesteps
    timezone: -6  # MDT (UTC-6)
    start_time: 2025/01/01 00:00:00
technology_interconnections:
  # supply the battery with electricity feedstock
  - [electricity_feedstock, battery, electricity, cable]
tech_to_dispatch_connections:
  - [electricity_feedstock, battery]
  - [battery, battery]
