name: plant_config
description: This plant is located of the coast of Galveston in Texas
sites:
  site:
    latitude: 29.2
    longitude: -94.6
    resources:
      wind_resource:
        resource_model: WTKNLRDeveloperAPIWindResource
        resource_parameters:
          resource_year: 2013
# this will naturally grow as we mature the interconnected tech
technology_interconnections:
  - [wind, electricity_splitter, electricity, cable]
  - [electricity_splitter, doc, electricity, cable]
  - [electricity_splitter, electrolyzer, electricity, cable]
  - [electrolyzer, h2_storage, hydrogen, pipe]
  # combine the h2 from the electrolyzer and the h2_storage
  - [electrolyzer, h2_combiner, hydrogen, pipe]
  - [h2_storage, h2_combiner, hydrogen, pipe]
  # connect the h2 supply to the methanol system
  - [h2_combiner, methanol, hydrogen, pipe]
  # connect the doc to co2 storage
  - [doc, co2_storage, co2, pipe]
  # combine the co2 from the doc and the co2_storage
  - [doc, co2_combiner, co2, pipe]
  - [co2_storage, co2_combiner, co2, pipe]
  # connect the co2 supply to the methanol system
  - [co2_combiner, methanol, co2, pipe]
resource_to_tech_connections:
  # connect the wind resource to the wind technology
  - [site.wind_resource, wind, wind_resource_data]
plant:
  plant_life: 30
  grid_connection: true  # option, can be turned on or off
  ppa_price: 0.027498168  # based off correlations of LBNL PPA data
  hybrid_electricity_estimated_cf: 0.492  # should equal 1 if grid_connection = True
finance_parameters:
  finance_groups:
    commodity: methanol
    finance_model: ProFastLCO
    model_inputs:
      params:
        analysis_start_year: 2032
        installation_time: 36  # months
        inflation_rate: 0.0  # 0 for nominal analysis
        discount_rate: 0.09  # nominal return based on 2024 ATB basline workbook for land-based wind
        debt_equity_ratio: 2.62  # 2024 ATB uses 72.4% debt for land-based wind
        property_tax_and_insurance: 0.03  # https://www.house.mn.gov/hrd/issinfo/clsrates.aspx
        total_income_tax_rate: 0.308  # 0.257 tax rate in 2024 atb baseline workbook, value here is based on federal (21%) and state in MN (9.8)
        capital_gains_tax_rate: 0.15  # H2FAST default
        sales_tax_rate: 0.07375  # total state and local sales tax in St. Louis County https://taxmaps.state.mn.us/salestax/
        debt_interest_rate: 0.07  # based on 2024 ATB nominal interest rate for land-based wind
        debt_type: Revolving debt  # can be "Revolving debt" or "One time loan". Revolving debt is H2FAST default and leads to much lower LCOH
        loan_period_if_used: 0  # H2FAST default, not used for revolving debt
        cash_onhand_months: 1  # H2FAST default
        admin_expense: 0.00  # percent of sales H2FAST default
      capital_items:
        depr_type: MACRS   # can be "MACRS" or "Straight line"
        depr_period: 5  # 5  y
  cost_adjustment_parameters:
    cost_year_adjustment_inflation: 0.025  # used to adjust modeled costs to target_dollar_year
    target_dollar_year: 2022
