name: technology_config
description: This hybrid plant produces methanol
technologies:
  wind:
    performance_model:
      model: PYSAMWindPlantPerformanceModel
    cost_model:
      model: GenericConverterCostModel
    model_inputs:
      performance_parameters:
        num_turbines: 24
        turbine_rating_kw: 15000
        rotor_diameter: 240.
        hub_height: 115.
        create_model_from: default
        config_name: WindPowerSingleOwner
        run_recalculate_power_curve: true
        pysam_options:
          Turbine:
            wind_resource_shear: 0.14
          Farm:
            wind_farm_wake_model: 0.0
            wind_resource_turbulence_coeff: 0.1
          Losses:
            elec_eff_loss: 1.79442  # less than 1.81, greater than 1.75
          Resource:
            weibull_k_factor: 2.0
            weibull_reference_height: 50.0
            weibull_wind_speed: 7.25
            wind_resource_model_choice: 0.0
          Uncertainty:
            total_uncert: 12.085
        layout:
          layout_mode: basicgrid
          layout_options:
            row_D_spacing: 7.0
            turbine_D_spacing: 7.0
            rotation_angle_deg: 0.0
            row_phase_offset: 0.0
            layout_shape: square
      cost_parameters:
        commodity: electricity
        commodity_rate_units: kW
        commodity_amount_units: kW*h
        unit_capex: 1380.0  # USD/kW
        unit_opex: 29.0  # USD/kW/year
        unit_varopex: 0.0  # USD/kWh
        cost_year: 2019
  electricity_splitter:
    performance_model:
      model: GenericSplitterPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: electricity
        commodity_rate_units: kW
        split_mode: fraction
        fraction_to_priority_tech: 0.243998425816608
  electrolyzer:
    performance_model:
      model: ECOElectrolyzerPerformanceModel
    cost_model:
      model: SingliticoCostModel
    model_inputs:
      shared_parameters:
        location: onshore
        electrolyzer_capex: 1295  # $/kW overnight installed capital costs for a 1 MW system in 2022 USD/kW (DOE hydrogen program record 24005	Clean Hydrogen Production Cost Scenarios with PEM Electrolyzer Technology 05/20/24) (https://www.hydrogen.energy.gov/docs/hydrogenprogramlibraries/pdfs/24005-clean-hydrogen-production-cost-pem-electrolyzer.pdf?sfvrsn=8cb10889_1)
      performance_parameters:
        size_mode: normal
        n_clusters: 4
        cluster_rating_MW: 40
        eol_eff_percent_loss: 10  # eol defined as x% change in efficiency from bol
        uptime_hours_until_eol: 80000  # number of 'on' hours until electrolyzer reaches eol
        include_degradation_penalty: true  # include degradation
        turndown_ratio: 0.1  # turndown_ratio = minimum_cluster_power/cluster_rating_MW
      financial_parameters:
        capital_items:
          depr_period: 7  # based on PEM Electrolysis H2A Production Case Study Documentation estimate of 7 years. also see https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
          replacement_cost_percent: 0.15  # percent of capex - H2A default case
  h2_storage:
    performance_model:
      model: StoragePerformanceModel
    cost_model:
      model: GenericStorageCostModel
    control_strategy:
      model: DemandOpenLoopStorageController
    model_inputs:
      shared_parameters:
        commodity: hydrogen
        commodity_rate_units: kg/h
        max_charge_rate: 50000.0  # kg/time step
        max_capacity: 103701.401563086  # kg
        max_soc_fraction: 1.0  # fraction (0-1)
        min_soc_fraction: 0.1  # fraction (0-1)
        init_soc_fraction: 0.25  # fraction (0-1)
        max_discharge_rate: 5000.0  # kg/time step
        charge_equals_discharge: false
        charge_efficiency: 1.0  # fraction (0-1)
        discharge_efficiency: 1.0  # fraction (0-1)
        demand_profile: 2108.73919484047
      cost_parameters:
        cost_year: 2022
        capacity_capex: 383  # $/kg - based on https://www.hydrogen.energy.gov/docs/hydrogenprogramlibraries/pdfs/review22/st235_houchins_2022_p-pdf.pdf?Status=Master
        charge_capex: .000001  # $/kg/h
        opex_fraction: .000001  # percent of capex
  h2_combiner:
    performance_model:
      model: GenericCombinerPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: hydrogen
        commodity_rate_units: kg/h
  doc:
    performance_model:
      model: DOCPerformanceModel
    cost_model:
      model: DOCCostModel
    model_inputs:
      shared_parameters:
        power_single_ed_w: 2858628.25565643  # W
        flow_rate_single_ed_m3s: 0.075  # m^3/s
        number_ed_min: 1
        number_ed_max: 10
        E_HCl: 0.05  # kWh/mol
        E_NaOH: 0.05  # kWh/mol
        y_ext: 0.9
        y_pur: 0.2
        y_vac: 0.6
        frac_ed_flow: 0.01
        use_storage_tanks: true
        initial_tank_volume_m3: 0.0  # m^3
        store_hours: 12.0  # hours
        sal: 33.0  # ppt
        temp_C: 12.0  # degrees Celsius
        dic_i: 0.0022  # mol/L
        pH_i: 8.1  # initial pH
      performance_parameters:
        save_plots: true
        save_outputs: true
      cost_parameters:
        infrastructure_type: desal
  co2_storage:
    performance_model:
      model: StoragePerformanceModel
    cost_model:
      model: GenericStorageCostModel
    control_strategy:
      model: DemandOpenLoopStorageController
    model_inputs:
      shared_parameters:
        commodity: co2
        commodity_rate_units: kg/h
        max_charge_rate: 50000.0  # kg/time step
        max_capacity: 961456.376748904  # kg
        max_soc_fraction: 1.0  # fraction (0-1)
        min_soc_fraction: 0.1  # fraction (0-1)
        init_soc_fraction: 0.25  # fraction (0-1)
        max_discharge_rate: 50000.0  # kg/time step
        charge_efficiency: 1.0  # fraction (0-1)
        discharge_efficiency: 1.0  # fraction (0-1)
        demand_profile: 15388.3891
      cost_parameters:
        cost_year: 2022
        capacity_capex: 5  # $/kg - based on https://www.maritime.dot.gov/sites/marad.dot.gov/files/2024-11/LCE%20MARAD%20CCS%20TEA%20Final%20Report%20-%2031%20May%202024%20%283%29.pdf
        charge_capex: .000001  # $/kg/h
        opex_fraction: .000001  # percent of capex
  co2_combiner:
    performance_model:
      model: GenericCombinerPerformanceModel
    model_inputs:
      performance_parameters:
        commodity: co2
        commodity_rate_units: kg/h
  methanol:
    performance_model:
      model: CO2HMethanolPlantPerformanceModel
    cost_model:
      model: CO2HMethanolPlantCostModel
    model_inputs:
      shared_parameters:
        plant_capacity_kgpy: 94731053.0605257
        plant_capacity_flow: methanol
      performance_parameters:
        capacity_factor: 1
        co2e_emit_ratio: 0.020296
        h2o_consume_ratio: 0.988
        h2_consume_ratio: 0.195
        co2_consume_ratio: 1.423
        elec_consume_ratio: 0.09466667
        meoh_syn_cat_consume_ratio: 0.00000128398
        ng_consume_ratio: 0.073511601
      cost_parameters:
        ng_lhv: 47.1
        toc_kg_y: 1.0633873
        foc_kg_y2: 0.020743864
        voc_kg: 0.00079
        meoh_syn_cat_price: 615.274273
        ng_price: 4.0
        co2_price: 0.0549007
        cost_year: 2020
